### ISSUE TITLE
Not linked

### ISSUE THREAD

**Issue by kochev** [thefex/Xamarin.Bindings.AdvancedRecyclerView#13]
> error XALNK7000: Mono.Linker.MarkException: Error processing method: 'Java.Lang.Object MvvmCross.AdvancedRecyclerView.Adapters.MvxHeaderFooterWrapperAdapter::OnCreateFooterItemViewHolder(Android.Views.ViewGroup,System.Int32)' in assembly: 'MvvmCross.AdvancedRecyclerView.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerViewHolder::set_Click(System.Windows.Input.ICommand)

catched when set "Link only SDK"
version 1.15.4
MvvmCross.Droid.Support.V7.RecyclerView version 6.4.2

**Comment by kochev** [comment]
with MvvmCross.Droid.Support.V7.RecyclerView version 6.2.0 worked all right

**Comment by thefex** [comment]
I had update ready but I found out that versions that MvvmCross versions that are not compatibile with current AdvancedRecyclerView have nasty issue that makes it unusable anyway.. 

https://github.com/MvvmCross/MvvmCross/commit/f97c92b31fecfd0046db066bf150fd61b768d633

Basically - ItemClick action is registered twice with MvvmCross.RecyclerView update, therefore command will be executed twice.

Thus, I am not publishing update until it is get fixed. As Mvx (7.0) is migrating towards AndroidX - update for AdvancedRecyclerView with MvvmCross 7.0 will be available.
