### ISSUE TITLE
Support AndroidX recycler view adapter

### ISSUE THREAD

**Issue by kochev** [thefex/Xamarin.Bindings.AdvancedRecyclerView#14]
Now recyclerView.NonExpandableAdapter is null if update project to AndroidX packages

**Comment by thefex** [comment]
As far as I know mvvmcross does not currently support AndroidX

**Comment by alexshikov** [comment]
Note:
There is 6.5.0 preview version with support of AndroidX in myget alpha channel.

**Comment by alexshikov** [comment]
Created PR https://github.com/thefex/Xamarin.Bindings.AdvancedRecyclerView/pull/15

**Comment by thefex** [comment]
Thanks for PR - but not sure will I merge that as there is simpler way to implement AndroidX support
Orginal AdvancedRecycler java library has update with AndroidX support so perhaps I will just bind AndroidX supported version and update some MvvmCross references

I should do that till the end of this month

**Comment by alexshikov** [comment]
Just a few notes: 
- the new AdvancedRecycler library with AndroidX support is already a part of this PR
- but the referenced MvvmCross alpha builds are hosted on myget.org and they are cleared too often (so they are not available at that time). We should switch to GitHub Registry or wait for official release of MvvmCross

**Comment by LDan1117** [comment]
Hi @thefex!

MvvmCross supporting AndroidX has been released quite for a while. Are there any plans on enabling the support of AndroidX RecyclerView adapters in AdvancedRecycler lib? Would you mind considering a PR from the community with such changes?

**Comment by thefex** [comment]
Library has bee nupdated to Mvx 8 and AndroidX
