### ISSUE TITLE
All Clicks don't work on v 1.16.2

### ISSUE THREAD

**Issue by Nikdm46** [thefex/Xamarin.Bindings.AdvancedRecyclerView#17]
All Clicks don't work on v 1.16.2

    For Header Click/LongClick bind to: HeaderClickCommand/HeaderLongClickCommand

    For Footer Click/LongClick bind to: FooterClickCommand/FooterLongClickCommand

    For Item Click (non expandable/grouped recyclerview) bind to: ItemClick/ItemLongClick

    For Group Item Click ( expandable/grouped recyclerview) bind to: GroupItemClick/GroupItemLongClick

    For Child Item Click ( expandable / grouped recyclerview) bind to: ChildItemClick/ChildItemLongClick

**Comment by NeuronKarrde** [comment]
As I investigated, click subscribing changed in MvxAdvancedRecyclerViewHolder(moved to OnAttachedToWindow). But OnAttachedToWindow method never invokes

**Comment by NeuronKarrde** [comment]
Oh, found one workaround. You can subscribe to ChildItemBound and GroupItemBound and call OnAttachedToWindow
 public override void OnStart()
      {
          base.OnStart();
          _recyclerView.ExpandableItemAdapter.ChildItemBound += ExpandableItemAdapterOnChildItemBound;
      }
        
      public override void OnStop()
      {
          base.OnStop();
          _recyclerView.ExpandableItemAdapter.ChildItemBound -= ExpandableItemAdapterOnChildItemBound;
      }

      private void ExpandableItemAdapterOnChildItemBound(MvxExpandableItemAdapterBoundedArgs obj)
      {
         obj.ViewHolder.OnAttachedToWindow();
      }

**Comment by evgenyvalavin** [comment]
Came across the same problem. Doesn't work since 1.16.1 for me

**Comment by MaximST92** [comment]
@NeuronKarrde Thanks for the workaround.
Is there a version planned where this issue will be resolved?

**Comment by thefex** [comment]
Fixed.
