### ISSUE TITLE
MvvmCross update to 8.0.0 breaks the AdvancedRecyclerView

### ISSUE THREAD

**Issue by asoodz** [thefex/Xamarin.Bindings.AdvancedRecyclerView#19]
_advanceRecyclerView = FindViewById<MvxAdvancedRecyclerView>(Resource.Id.customize_options);
            _advanceRecyclerView.AddItemDecoration(new AdvancedRecyclerViewSeparator(this));
            var mvxExpandableItemAdapter = _advanceRecyclerView.AdvancedRecyclerViewAdapter as MvxExpandableItemAdapter;
            
In the above code, mvxExpandableItemAdapter returns null.
<img width="962" alt="Screen Shot 2021-07-20 at 4 04 47 pm" src="https://user-images.githubusercontent.com/45929273/126273175-ec64a973-01bf-467f-be9b-9dd68a60cccc.png">

**Comment by thefex** [comment]
Library has been updated to Mvx 8 and AndroidX
