### ISSUE TITLE
Bug: NoClassDefFoundError AnimatorCompatHelper

### ISSUE THREAD

**Issue by KennethKr** [thefex/Xamarin.Bindings.AdvancedRecyclerView#4]
App crashes on buildtools v26 with oreo sdk:  NoClassDefFoundError AnimatorCompatHelper

Probably same crash as https://github.com/h6ah4i/android-advancedrecyclerview/issues/413

0.11 fixes the problem. Migration guide: https://github.com/h6ah4i/android-advancedrecyclerview/issues/425

**Comment by thefex** [comment]
thx, it's fixed in: https://www.nuget.org/packages/MvvmCross.AdvancedRecyclerView/1.11.0 :)
