### ISSUE TITLE
Add Move and Replace event support in MvxRecyclerViewItemsSourceBridge

### ISSUE THREAD

**Issue by JensSchadron** [thefex/Xamarin.Bindings.AdvancedRecyclerView#9]
The Move and Replace events from NotifyCollectionChangedAction aren't impemented in [MvxRecyclerViewItemsSourceBridge](https://github.com/thefex/Xamarin.Bindings.AdvancedRecyclerView/blob/91592b7644a5735848c8ebd32eb3cabe739963f3/AdvancedRecyclerView/MvvmCross.AdvancedRecyclerView/Data/MvxRecyclerViewItemsSourceBridge.cs#L63) so it's impossible to directly update an item at the time of writing.

In my case, it's necessary as sometimes the entire item as passed through into a valueconverter because of the amount of properties are needed to decide onto the correct output value. However I need to trigger the Reset event in my case in order to update a header in the MvxAdvancedExpandableRecyclerView.

**Comment by thefex** [comment]
I planned to that but I would need about ~10-20 work hours to implement that properly (first implementation try failed - it is rather difficult to do that GOOD)

Nevertheless, I usually pass whole object as "Key" which has INotifyPropertyChanged so I can update header dynamically without resetting state.
Besides, it seems that move/replace animation works even without supporting those events - please check updated samples with DynamicData.

**Comment by JensSchadron** [comment]
I tried your advice (back when you posted your answer here) and it works pretty well.
Forgot to close the issue though, so I'll do that now.
